export enum ColumnsType {
    PrimaryKey,
    PrimaryAutoGeneratedKey,
    Data,
    Relation
}

export interface ColumnInfo {
    name: string,
    type?: ColumnsType,
    length?: number
}